Repository ROCm/rocJPEG, pull requests merged in 2024-12, with the labels that each got.

#87 Don't use dummy surface for vaCreateContext
  src/rocjpeg_vaapi_decoder.cpp
  src/rocjpeg_vaapi_decoder.h
Labels: ci:precheckin

#92 Use VA_FOURCC_YUY2 instead of YUYV
  src/rocjpeg_decoder.cpp
  src/rocjpeg_vaapi_decoder.cpp
  src/rocjpeg_vaapi_decoder.h
Labels: ci:precheckin

#96 External CI: create CI triggers file
  .azuredevops/rocm-ci.yml
Labels: noCI

#88 Create surfaces with linear modifier
  src/rocjpeg_vaapi_decoder.cpp
  src/rocjpeg_vaapi_decoder.h
Labels: ci:precheckin

#95 Adding documentation
  .readthedocs.yaml
  README.md
  docs/how-to/rocjpeg-decoding-a-jpeg-stream.rst
  docs/how-to/rocjpeg-retrieve-image-info.rst
  docs/how-to/using-rocjpeg.rst
  docs/index.rst
  docs/install/install.rst
  docs/install/quick-start.rst
  docs/install/rocjpeg-build-and-install.rst
  docs/install/rocjpeg-package-install.rst
  docs/install/rocjpeg-prerequisites.rst
  docs/reference/rocjpeg-formats-and-architectures.rst
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: enhancement, ci:docs-only

#98 Increase the output image sizes
  samples/rocjpeg_samples_utils.h
Labels: bugfix, ci:precheckin

#97 Enable the CMake ROCJPEG_ROCPROFILER_REGISTER option by default
  CMakeLists.txt
Labels: ci:precheckin
