Repository ROCm/rocJPEG, pull requests merged in 2025-03, with the labels that each got.

#124 Package - Updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docker/rocJPEG-on-ubuntu20.dockerfile
  docs/install/rocjpeg-prerequisites.rst
Labels: enhancement, ci:precheckin

#127 CTEST - add new tests
  CHANGELOG.md
  CMakeLists.txt
  api/rocjpeg_version.h
  test/CMakeLists.txt
Labels: ci:precheckin

#128 CMake Modules - Config Files and version
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  api/rocjpeg.h
  api/rocjpeg_version.h.in
  cmake_modules/rocjpeg-config.cmake.in
  rocJPEG-setup.py
Labels: enhancement, ci:precheckin, new feature

#129 Find rocJPEG - Updates
  CMakeLists.txt
  api/amd_detail/rocjpeg_api_trace.h
  api/rocjpeg/rocjpeg.h
  cmake/FindrocJPEG.cmake
  cmake_modules/rocjpeg-config.cmake.in
  docs/doxygen/Doxyfile
  samples/jpegDecode/CMakeLists.txt
  samples/jpegDecodeBatched/CMakeLists.txt
  samples/jpegDecodePerf/CMakeLists.txt
  samples/rocjpeg_samples_utils.h
  src/rocjpeg_decoder.h
  src/rocjpeg_vaapi_decoder.h
  test/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin

#131 Version updates: Update rocjpeg_version.h.in
  api/rocjpeg_version.h.in
Labels: bugfix, ci:precheckin

#134 Package - Dev install fix
  CMakeLists.txt
Labels: bugfix, ci:precheckin
