Repository ROCm/rocJPEG, pull requests merged in 2025-04, with the labels that each got.

#138 CI Update - Enhance testing for rocJPEG by using JPEG images with different chroma subsampling options
  .jenkins/common.groovy
Labels: enhancement, ci:precheckin

#143 CTest: Add a test to perform negative testing on all rocJPEG APIs
  CMakeLists.txt
  src/rocjpeg_decoder.cpp
  test/CMakeLists.txt
  test/rocjpeg_negative_api_tests/CMakeLists.txt
  test/rocjpeg_negative_api_tests/README.md
  test/rocjpeg_negative_api_tests/rocjpeg_api_negative_tests.cpp
  test/rocjpeg_negative_api_tests/rocjpeg_api_negative_tests.h
  test/rocjpeg_negative_api_tests/rocjpegnegativetest.cpp
Labels: ci:precheckin

#144 Test: update TestInvalidGetErrorName test to cover all possible error names
  api/rocjpeg/rocjpeg.h
  test/rocjpeg_negative_api_tests/rocjpeg_api_negative_tests.cpp
Labels: ci:precheckin

#145 CMakeLists - Fix CXX Std
  CMakeLists.txt
  samples/jpegDecode/CMakeLists.txt
  samples/jpegDecodeBatched/CMakeLists.txt
  samples/jpegDecodePerf/CMakeLists.txt
  test/CMakeLists.txt
  test/rocjpeg_negative_api_tests/CMakeLists.txt
Labels: bugfix, ci:precheckin
